const dictionary = {
    // Arv
    "arv": "число",
    "paaritu arv": "нечётное число",
    "paarisarv": "чётное число",
    "algarv": "простое число",
    "kordarv": "составное число",
    "negatiivne arv": "отрицательное число",
    "positiivne arv": "положительное число",
    "arvu kordsed": "кратные числа",
    "arvu tegurid": "делители числа",
    "naturaalarv": "натуральное число",
    "täisarv": "целое число",
    "ratsionaalarv": "рациональное число",
    "irratsionaalarv": "иррациональное число",
    "reaalarv": "действительное число",
    "ligikaudne arv": "приблизительное число",
    "segaarv": "смешанное число",
    "murdarv": "дробное число",
    "vastandarv": "противоположное число",
    "pöördarv": "обратное число",
    "arvkiir": "числовой луч",
    "arvukuup": "куб числа",
    "ühiskordne arv": "общее кратное числа",
    
    // Murd
    "murd": "дробь",
    "harilik murd": "обыкновенная дробь",
    "murru lugeja": "числитель дроби",
    "murru nimetaja": "знаменатель дроби",
    "kümnendmurd": "десятичная дробь",
    "kümnendmurru murdosa": "дробная часть десятичной дроби",
    "kümnendmurru täisosa": "целая часть десятичной дроби",
    "kümnendmurru ümardamine": "округление десятичной дроби",
    "murru laiendaja": "дополнительный множитель",
    "murru laiendamine": "расширение дроби",
    "murru taandamine": "сокращение дроби",
    "erinimelised murrud": "дроби с разными знаменателями",
    "perioodiline kümnendmurd": "периодическая десятичная дробь",
    "lõplik murd": "конечная дробь",
    "lõpmatu murd": "бесконечная дробь",
    "ühine nimetaja": "общий знаменатель",
    
    // Statistika
    "statistika": "статистика",
    "andmed": "данные",
    "andmehulga karakteristikud": "характеристики",
    "aritmeetiline keskmine": "среднее арифметическое",
    "diagramm": "диаграмма",
    "mediaan": "медиана",
    "mood": "мода",
    "protsent": "процент",
    "sagedus": "частота",
    "suhteline sagedus": "относительная частота",
    "sagedustabel": "частотная таблица",
    "skaala": "шкала",
    "sektordiagramm": "секторная (круговая) диаграмма",
    "tulpdiagramm": "столбчатая диаграмма",
    
    // Tehted
    "tehted": "действия",
    "lahutamine": "вычитание",
    "vähendav": "вычитаемое",
    "vähendaja": "уменьшаемое",
    "vahe": "разность",
    "liitmine": "сложение",
    "liidetav": "слагаемое",
    "summa": "сумма",
    "jagamine": "деление",
    "jagatav": "делимое",
    "jagaja": "делитель",
    "jagatis": "частное",
    "korrutamine": "умножение",
    "tegur": "множитель",
    "korrutis": "произведение",
    "juurimine": "извлечение корня",
    "juur": "корень",
    "juurija": "показатель корня",
    "juuritav": "подкоренное число",
    "tegurdamine": "разложение на множители",
    "koondamine": "приведение подобных",
    "arvandmete korrastamine": "упорядочение числовых значений",
    "võrdlemine": "сравнение",
    "sulgude avamine": "раскрытие скобок",
    "sulgude ette toomine": "вынесение за скобки",
    "ümardamine": "округление",
    "astendamine": "возведение в степень",
    "absoluutväärtus": "модуль",
    "võrrandi lahendus": "решение уравнения",
    "võrrand": "уравнение",
    "hulkliige": "многочлен",
    "üksliige": "одночлен",
    
    // Tehted astmetega
    "tehted astmetega": "действия со степенями",
    "aste": "степень",
    "astendaja": "показатель степени",
    "astme alus": "основание степени",
    "astme ruutjuur": "квадратный корень степени",
    "võrdsete alustega astmete korrutamine": "умножение степеней с равными основаниями",
    "võrdsete alustega astmete jagamine": "деление степеней с равными основаниями",
    "korrutise astendamine": "возведение произведения в степень",
    "jagatise astendamine": "возведение частного в степень",
    "astme astendamine": "возведение степени в степень",
    
    // Tõenäosus
    "tõenäosus": "вероятность",
    "juhuslik sündmus": "случайное событие",
    "katse": "испытание",
    "kindel sündmus": "достоверное событие",
    "mittevälistavad sündmused": "совместные события",
    "sündmus": "событие",
    "sõltuvad sündmused": "зависимые события",
    "sõltumatud sündmused": "независимые события",
    "soodne võimalus": "благоприятная возможность",
    "tulemus": "результат",
    "välistavad sündmused": "несовместные события",
    "võimatu sündmus": "невозможное событие",
    
    // Valemid
    "valemid": "формулы",
    "summa ruut": "квадрат суммы",
    "vahe ruut": "квадрат разности",
    "ruutude summa": "сумма квадратов",
    "ruutude vahe": "разность квадратов",
    "summa ruudu valem": "формула квадрата суммы",
    "vahe ruudu valem": "формула квадрата разности",
    "summa kuubi valem": "формула куба суммы",
    "vahe kuubi valem": "формула куба разности",
    "kuupide summa valem": "формула суммы кубов",
    "kuupide vahe valem": "формула разности кубов",
    "korrutise ruutjuur": "квадратный корень произведения",
    "jagatise ruutjuur": "квадратный корень частного",
    
    // Geomeetrilised kujundid
    "geomeetrilised kujundid": "геометрические фигуры",
    "pindala": "площадь",
    "ümbermõõt": "периметр",
    "ruumala": "объем",
    "ring": "круг",
    "ringi sektor": "сектор круга",
    "ringi pindala": "площадь круга",
    "ringjoon": "окружность",
    "ringjoone diameeter": "диаметр окружности",
    "ringjoone läbimõõt": "диаметр окружности",
    "ringjoone keskpunkt": "центр окружности",
    "ringjoone raadius": "радиус окружности",
    "ringjoone pikkus": "длина окружности",
    "ristkülik": "прямоугольник",
    "pikkus": "длина",
    "laius": "ширина",
    "ristküliku pindala": "площадь прямоугольника",
    "ristküliku ümbermõõt": "периметр прямоугольника",
    "ruut": "квадрат",
    "ruudu pindala": "площадь квадрата",
    "ruudu ümbermõõt": "пеметр квадрата",
    "ruudu diagonaal": "диагональ квадрата",
    "kolmnurk": "треугольник",
    "lähiskülg": "прилежащая сторона",
    "vastaskülg": "противолежащая сторона",
    "erikülgne kolmnurk": "разносторонний треугольник",
    "kolmnurga ümbermõõt": "периметр треугольника",
    "kõrgus": "высота",
    "alus": "основание",
    "kolmnurga pindala": "площадь треугольника",
    "täisnurkne kolmnurk": "прямоугольный треугольник",
    "täisnurkse kolmnurga pindala": "площадь прямоугольного треугольника",
    "Viète'i teoreem": "теорема Виета",
    "diskriminant": "дискриминант",
    "trigonomeetria": "тригонометрия",
    "teravnurga siinus": "синус острого угла",
    "teravnurga koosinus": "косинус острого угла",
    "teravnurga tangens": "тангенс острого угла",
    "teravnurga kootangens": "котангенс острого угла",
    "hüpotenuus": "гипотенуза",
    "kaatet": "катет",
    "romb": "ромб",
    "rombi diagonaalide omadus": "свойство диагоналей ромба",
    "rombi pindala": "площадь ромба",
    "rombi ümbermõõt": "периметр ромба",
    "rööpkülik": "параллелограмм",
    "rööpküliku alus": "основание параллелограмма",
    "rööpküliku kõrgus": "высота параллелограмма",
    "rööpküliku ümbermõõt": "периметр параллелограмма",
    "rööpküliku pindala": "площадь параллелограмма",
    "trapets": "трапеция",
    "trapetsi ümbermõõt": "периметр трапеции",
    "trapetsi pindala": "площадь трапеции",
    "võrdhaarne trapets": "равнобедренная трапеция",
    "täisnurkne trapets": "прямоугольная трапеция",
    "tasand": "плоскость",
    "kera": "шар",
    "kera pindala": "площадь поверхности шара",
    "kera ruumala": "объем шара",
    "koonus": "конус",
    "koonuse täispindala": "площадь полной поверхности конуса",
    "koonuse külgpindala": "площадь боковой поверхности конуса",
    "koonuse ruumala": "объем конуса",
    "püramiid": "пирамида",
    "korrapärane püramiid": "правильная пирамида",
    "püramiidi ruumala": "объем пирамиды",
    "püramiidi külgpindala": "площадь боковой поверхности пирамиды",
    "püramiidi täispindala": "площадь полной поверхности пирамиды",
    "silinder": "цилиндр",
    "silindri täispindala": "площадь полной поверхности цилиндра",
    "silindri külgpindala": "площадь боковой поверхности цилиндра",
    "silindri ruumala": "объем цилиндра",
    "risttahukas": "прямоугольный параллелепипед",
    "risttahuka ruumala": "объем параллелепипеда",
    "risttahuka täispindala": "площадь полной поверхности прямоугольного параллелепипеда",
    
    // Graafik
    "graafik": "график",
    "abstsiss": "абсцисса",
    "abstsisstelg": "ось абсцисс",
    "ordinaat": "ордината",
    "ordinaattelg": "ось ординат",
    "koordinaat": "координата",
    "koordinaatide alguspunkt": "начало координат",
    "võrdeline sõltuvus": "прямая пропорциональность",
    "lineaarfunktsioon": "линейная функция",
    "ruutfunktsioon": "квадратичная функция",
    "taandamata ruutvõrrand": "неприведенное квадратное уравнение",
    "taandatud ruutvõrrand": "приведенное квадратное уравнение",
    "mittetäielik ruutvõrrand": "неполное квадратное уравнение",
    "täielik ruutvõrrand": "полное квадратное уравнение",
    "parabool": "парабола",
    "nullpunkt": "начало координат",
    "nullkohad": "нули функции",
    "negatiivne suund": "отрицательное направление",
    "positiivne suund": "положительное направление",
    "parabooli haripunkt": "вершина параболы",
    "parabooli sümmeetriatelg": "ось симметрии параболы",
    "sümmeetria": "симметрия",
    "hüperbool": "гипербола",
    "hüperbooli harud": "ветви гиперболы",
    "pöördvõrdeline sõltuvus": "обратная пропорциональность",
    
    // Meetermõõdustik ühikusüsteem
    "meetermõõdustik ühikusüsteem": "метрическая система единиц",
    "meeter": "метр",
    "millimeeter": "миллиметр",
    "santimeeter": "сантиметр",
    "detsimeeter": "дециметр",
    "kilomeeter": "километр",
    "dekameeter": "декаметр",
    "hektomeeter": "гектометр",
    "gramm": "грамм",
    "kilogramm": "килограмм",
    "milligramm": "миллиграмм",
    "tonn": "тонна",
    "liiter": "литр",
    "milliliiter": "миллилитр",
    "santiliiter": "сантилитр",
    "detsiliiter": "децилитр",
    "millisekund": "миллисекунда",
    "sekund": "секунда",
    "minut": "минута",
    "tund": "час",
    
    // Nurk
    "nurk": "угол",
    "nurga haar": "сторона угла",
    "nurga tipp": "вершина угла",
    "nürinurk": "тупой угол",
    "sirgnurk": "развернутый угол",
    "teravnurk": "острый угол",
    "täisnurk": "прямой угол",
    "täispööre": "полный угол",
    "nurgakraad": "градус угла",
    "nurgaminut": "минута угла",
    "nurgasekund": "секунда угла",
    
    // Sirged ja lõikused
    "sirged ja lõikused": "прямые и отрезки",
    "lõik": "отрезок",
    "lõigu pikkus": "длина отрезка",
    "kiir": "луч",
    "sirge": "прямая",
    "joon": "линия",
    "lõikuvad sirged": "пересекающиеся прямые",
    "murdjoon": "ломаная",
    "paralleelsed sirged": "параллельные прямые",
    "ristuvad sirged": "перпендикулярные прямые",
    "lõigu keskpunkt": "середина отрезка",
    "keskristsirge": "серединный перпендикуляр",
    "puutuja": "касательная",
    "aksioom": "аксиома",
    "paralleelide aksioom": "аксиома о параллельности",
    "põiknurgad": "внутренние накрест лежащие углы",
    "lähisnurgad": "внутренние односторонние углы",
    "kaasnurgad": "соответственные углы"
};

let searchinput = document.getElementById("searchinput");
let searchbtn = document.getElementById("searchbtn");
let print = document.getElementById("print");

function searchWord() {
    const wordToSearch = searchinput.value.trim().toLowerCase();
    if (!wordToSearch) {
        print.innerHTML = "<p>Palun sisesta otsitav sõna.</p>";
        return;
    }

    let foundword = false;
    for (const [word, translation] of Object.entries(dictionary)) {
        if (word.toLowerCase().startsWith(wordToSearch)) {
            print.innerHTML = `<p><strong>${word}</strong> - ${translation}</p>`;
            foundword = true;
            break;
        }
    }

    if (!foundword) {
        print.innerHTML = "<p>Sõna ei leitud.</p>";
    }
}

searchinput.addEventListener('keydown', function (e) {
    if (e.key === 'Enter') searchWord();
});

